name: Integration Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  units:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        version: [2.9, '3.0', 3.1, 3.2, master]
        include:
        - os: ubuntu-18.04
          version: 2.8
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Clone MAAS repository
      run: git clone https://git.launchpad.net/maas -b ${{ matrix.version }} --depth 1
    - name: Install MAAS dependencies
      run: (cd ./maas && sudo make install-dependencies && sudo pip3 install -r requirements-dev.txt)
    - name: pip freeze
      run: pip3 freeze 
    - name: Run test
      run: sudo python3 -m unittest test.py