name: Integration Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  units:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        ceph: [quincy]
        include:
        - os: ubuntu-18.04
          ceph: pacific
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install ceph
      run: |
        sudo apt install ceph ceph-common cephadm
        sudo cephadm bootstrap --mon-ip $(hostname -i) --single-host-defaults
    - name: Run test
      run: ceph -s